// Generated by Wrangler by running `wrangler types`

interface Env {
	MARKET_CACHE: KVNamespace;
	HASH_CHAIN_CACHE: KVNamespace;
	GAMMA_API_URL: "https://gamma-api.polymarket.com";
	CLOB_WSS_URL: "wss://ws-subscriptions-clob.polymarket.com/ws/market";
	SNAPSHOT_INTERVAL_MS: "60000";
	ORDERBOOK_MANAGER: DurableObjectNamespace<import("./src/index").OrderbookManager>;
	DEAD_LETTER_QUEUE: Queue;
	SNAPSHOT_QUEUE: Queue;
	GAP_BACKFILL_QUEUE: Queue;
	TRADE_QUEUE: Queue;
	LEVEL_CHANGE_QUEUE: Queue;
	FULL_L2_QUEUE: Queue;
}
